version: "3.8"
services:
  cream-redis:
    image: redis:alpine
    container_name: cream-redis
    # environment:
    #   REDIS_PASSWORD: redispass
    ports:
      - 6379:6379
    networks:
      - cream-net
    user: redis

  cream-db:
    container_name: cream-db
    hostname: cream-db
    image: postgres:13
    volumes:
      - ./cream-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - cream-net

  cream-storage:
    image: minio/minio
    container_name: cream-storage
    hostname: cream-storage
    ports:
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_REGION=${MINIO_REGION}
    networks:
      - cream-net
    volumes:
      - ./cream-storage-data:/data
    command: server --address :9001 /data

  createbuckets:
    image: minio/mc
    depends_on:
      - cream-storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://cream-storage:9001 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/cream;
      /usr/bin/mc anonymous set public myminio/cream;
      exit 0;
      "
    networks:
      - cream-net

  cream-api:
    container_name: cream-api
    build:
      context: ./cream-api
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./cream-api/Caddyfile:/etc/caddy/Caddyfile
      - ./selfsigned.crt:/etc/caddy/certs/selfsigned.crt
      - ./selfsigned.key:/etc/caddy/certs/selfsigned.key
      - ./certs:/etc/caddy/certs/cream-fm.art
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_URL=${AWS_URL}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - FILESYSTEM_PUBLIC_DRIVER=${FILESYSTEM_PUBLIC_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - 8000:8000
      - 443:443
      - 80:80
      - 2015:2015
    depends_on:
      - cream-db
      - cream-storage
      - cream-redis
    networks:
      - cream-net

  cream-soap:
    container_name: cream-soap
    build:
      context: ./cream-soap
      dockerfile: Dockerfile
    working_dir: /home/liquidsoap
    volumes:
      - ./cream-soap/config:/home/liquidsoap/config
      - ./cream-soap/content:/home/liquidsoap/content
    environment:
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
    entrypoint: liquidsoap
    command: /home/liquidsoap/config/main.liq
    networks:
      - cream-net
    ports:
      - 1234:1234
      - 8002:8002

  cream-cast:
    container_name: cream-cast
    build:
      context: ./cream-cast
      dockerfile: Dockerfile
    volumes:
      - ./cream-cast/config:/home/icecast/config
      - ./cream-cast/log:/home/icecast/log
      - ./cream-cast/docker-entrypoint.sh:/home/icecast/docker-entrypoint.sh
    environment:
      - ICECAST_LOCATION=${ICECAST_LOCATION}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
      - ICECAST_RELAY_SERVER=${ICECAST_RELAY_SERVER}
    depends_on:
      - cream-api
    ports:
      - 8004:8004
    networks:
      - cream-net

  cream-tg:
    container_name: cream-tg
    hostname: cream-tg
    environment:
      - TEST_CHANNEL_BUCKET=${TEST_CHANNEL_BUCKET}
      - RTMP_URL=${RTMP_URL}
      - BOT_SUPERADMIN_ID=${BOT_SUPERADMIN_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - JWT_TOKEN=${JWT_TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
    build:
      context: ./cream-tg
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - 3005:3000
    networks:
      - cream-net
    volumes:
      - ./cream-tg:/app
      - ./selfsigned.crt:/app/selfsigned.crt
    depends_on:
      - cream-api

networks:
  cream-net:
    driver: bridge
