name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_WORKER_USERNAME }}
          password: ${{ secrets.SSH_WORKER_PASSWORD }}
          script: |



            echo "Stopping all running containers..."
            docker stop $(docker ps -q)



            echo "Pruning Docker system..."
            docker system prune -af



            DIRECTORY="cream"
            if [ -d "$DIRECTORY" ]; then
              echo "Removing existing 'cream' directory..."
              rm -rf "$DIRECTORY"
            fi



            echo "Cloning the 'cream' repository..."
            git clone https://github.com/dmeckers/cream



            cd cream
            echo "Initializing and updating submodules..."
            git submodule update --init --recursive
            git submodule foreach git pull origin main



            echo "Running Docker Compose..."
            docker-compose up -d --build
