name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_WORKER_USERNAME }}
          password: ${{ secrets.SSH_WORKER_PASSWORD }}
          script:
            # Commands to be executed on the remote server
            rm -rf cream
            git clone https://github.com/dmeckers/cream
            cd cream
            git submodule update --init --recursive
            docker-compose up -d
